openapi: 3.0.0 

info: 
  title: Sierra Impact API's 
  description: API dpcumentation for the collection and retireval microservices offered by Sierra Impact
  version: 1.0.0 
contact: 
  name: Jack Buchanan
  email: z5478552@ad.unsw.edu.au

servers: 
  - url: https://2vyhl58mci.execute-api.ap-southeast-2.amazonaws.com/1
  - description: Data Collection Endpoint 