name: Lint

on:
  # Trigger the workflow on push or pull request to main and production branches
  push:
    branches:
      - main
      - production
  pull_request:
    branches:
      - main
      - production

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run Python linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the appropriate Python version

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Run Flake8 (Checks for style issues)
        run: flake8 .

      - name: Run Black (Code formatting check)
        run: black --check .
